// export const AUTH_TOKEN  = "AUTH_TOKEN";
export const AUTH_SUCCESS  = "AUTH_SUCCESS";
// export const AUTH_LOGIN_RESPONSE_SUCCESS  = "AUTH_LOGIN_RESPONSE_SUCCESS";
// export const AUTH_LOGIN_RESPONSE_ERROR  = "AUTH_LOGIN_RESPONSE_ERROR";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
